# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :host1 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.10'
  },
  :host2 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.11'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          if boxname == "host1"
          box.vm.host_name = "dc.otustest.com"
          else
          box.vm.host_name = "client.otustest.com"
          end

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            #vb.customize ["modifyvm", :id, "--memory", "256"]
          end
          
          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
          SHELL

          box.vm.provision "ansible" do |ansible|
            #ansible.verbose = "vvvvv"
            ansible.inventory_path = "./hosts"
            ansible.playbook = "playbook.yml"
            ansible.become = "true"
          end

      end
  end
end
