---

 - name: Install NGINX soft
   yum:
      name: nginx
      state: latest
 - name: Enable nginx
   systemd:
      name: nginx
      enabled: yes
   notify: start nginx
 - name: update nginx config
   template:
      src: etc/nginx/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
   notify: restart nginx
